apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: gcr.io/google_containers/kube-apiserver:v1.6.1
    command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-apiserver 
      --insecure-bind-address=$THIS_IP
      --bind-address=0.0.0.0
      --etcd-servers=http://master1:2379,http://master2:2379,http://master3:2379
      --admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
      --service-cluster-ip-range=10.0.0.0/16 
      --cluster-name=kube-bmx-dbaas
      --client-ca-file=/etc/kubernetes/ssl/apiserver/ca.crt
      --tls-cert-file=/etc/kubernetes/ssl/apiserver/server.cert 
      --tls-private-key-file=/etc/kubernetes/ssl/apiserver/server.key
      --secure-port=443 
      --v=2
      --allow-privileged=False 1>>/var/log/kube-apiserver.log 2>&1
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 7080
      hostPort: 7080
      name: http
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl/apiserver/apiserver
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/kubernetes
      name: kubernetes-configfiles
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl/apiserver
    name: ssl-certs-kubernetes
  - hostPath:
      path: /etc/kubernetes
    name: kubernetes-configfiles
